site_name: COMP423 Course Notes
theme:
  name: material
  palette:
    - scheme: default
      primary: pink  
      accent: blue  
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

markdown_extensions:
  - admonition                  
  - pymdownx.highlight           
  - pymdownx.superfences           
  - pymdownx.tabbed               
  - pymdownx.tilde                 
  - pymdownx.tasklist             
  - pymdownx.emoji  