site_name: COMP423 Course Notes
theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      info: octicons/info-16

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences